name: pdf_stamp_editor
description: "PDF viewer with stamp overlays and native export layer (Android+iOS supported)."
version: 0.4.0
homepage: https://github.com/ondrahracek/flutter_pdf_stamp_editor
repository: https://github.com/ondrahracek/flutter_pdf_stamp_editor
issue_tracker: https://github.com/ondrahracek/flutter_pdf_stamp_editor/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  pdfrx: ^2.2.17
  image: ^4.0.0
  file_picker: ^10.3.7
  path_provider: ^2.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.ondrahracek.pdf_stamp_editor
        pluginClass: PdfStampEditorPlugin
      ios:
        pluginClass: PdfStampEditorPlugin
